name: uAT Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure CMake
      run: |
        cd tests
        mkdir build
        cd build
        cmake ..
        
    - name: Build
      run: |
        cd tests/build
        make
        
    - name: Run Tests
      run: |
        cd tests/build
        ctest --output-on-failure --verbose
        
    - name: Run Parser Tests Directly
      run: |
        cd tests/build
        ./test_parser
        
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: tests/build/Testing/Temporary/LastTest.log